### PR TITLE
Friends List

### PR DESCRIPTION
**Pull request by keithrpotempa**
The friend list and initial add-friend features are functional. 

1. `git fetch --all`
2. `git checkout kp-friends-list`
3. `git pull`

Check out the index page and confirm:
1. You can create a friendship with another existing user (by email address)
2. You can delete an existing friendship
3. You are prevented from creating a friendship for someone who doesn't exist 
4. You are prevented from creating a friendship for someone who you're already friends with

### CODE REVIEW

**Comment by keithrpotempa** [comment]
Please pull again; the 'already friend' issue should be resolved.

**Comment by castlesmadeofcode** [comment]
working!

**Comment by sncandiani** [comment]
After much work, it looks like most of it is working!

**Comment by castlesmadeofcode** [comment]
All functionality is working, looks great!

**Pull request merged**
