### PR TITLE
Chat messages cc5

### PR DESCRIPTION
**Pull request by castlesmadeofcode**
git fetch --all
git checkout chatMessagesCC5
make sure a new user can register an account, add a new message, and edit the new message.

### CODE REVIEW

**Comment by keithrpotempa** [comment]
I pulled this down, but I'm not seeing any of the user registration information in the browser... user__div is empty

I'm confused. Let's convene after lunch?

**Comment by sncandiani** [comment]
When 'create account' button is clicked it leads the user to only the email as opposed to the whole form. Also, the first time the button is clicked it is automatically stores as Keith. Other than that functionality seems to be working and storing to the database.

**Comment by keithrpotempa** [comment]
It's coming along! I can register a user and post messages as that user, but there are a two things I think should be updated before we merge. 

1. Login option (in addition to register). If a user clicks the login button/link, it presents a form to login. If a user enters a username and email that matches one in the database, they are "logged in" as that user (session storage active user is updated).
2. A method that checks the session storage for a logged in user at page load, and loads the page with that user logged in (if you refresh now, you are given the register user form, even though the session storage has an active user id).

**Comment by sncandiani** [comment]
It finally works!!! Amazing, after many commits you have done it!

**Comment by keithrpotempa** [comment]
👍 Looks great! Thanks for your diligent pioneering on this front.

**Pull request merged**
